import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../styles/globals.css";
import Header from "../components/major/Header"
import Footer from "../components/major/Footer";

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

const ancientGod = localFont({
  src: './fonts/Ancient God.woff2',
  display: 'swap',
})

const deSwash = localFont({
  src: './fonts/DevinneSwash.woff2',
  display: 'swap',
  variable: '--font-deSwash',
})

const spaceGames = localFont({
  src: './fonts/Space Games.woff2',
  display: 'swap',
  variable: '--font-spaceGames',
})

const fe = localFont({
  src: './fonts/FeFCrm2.woff2',
  display: 'swap',
  variable: '--font-fe',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ancientGod.className} ${spaceGames.variable} ${deSwash.variable} ${fe.variable}`}>
      <body
        className={` antialiased`}
      >
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
