import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../styles/globals.css";
import Header from "../components/shared/Header"
import Footer from "../components/shared/Footer";

const ancientGod = localFont({
  src: './fonts/Ancient God.woff2',
  display: 'swap',
})

const spaceGames = localFont({
  src: './fonts/Space Games.woff2',
  display: 'swap',
  variable: '--font-spaceGames',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ancientGod.className} ${spaceGames.variable}`}>
      <body
        className={` antialiased`}
      >
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
